### PR TITLE
Improve log window + other features

### PR DESCRIPTION
**Pull request by mclarence**
Log level is now set through `LOG_LEVEL` environment variable. If this variable is not set, the default level is INFO

Log window changes
- Logs are shown in list view instead of text area to improve perfomance.
- Logs can be exported to file.
- Logs can be cleared.

Other changes
- User can now specify plex server address + port manually.
- Auto login checkbox moved to settings.

Push to develop for now, there is more to come.

#33 
#31

### CODE REVIEW

**Comment by Ombrelin** [comment]
Hi Clarence,
you truly are awesome, thank you again for your contributions !
Is this ready for review and merge yet ?

**Comment by mclarence** [comment]
Yes I am done.

**Comment by Ombrelin** [comment]
Okay, neat ! 
I'll find some time through the weekend to integrate this.
Also, think I'll start to write a troubleshooting guide which sums up the issues encountered until now in order to save users and us some time

**Comment by mclarence** [comment]
Wait, do not merge yet. I've encountered a bug with the tray icon.

**Comment by mclarence** [comment]
Ok that should be it.

Please test if everything is working on your size as well.

**Pull request merged**
