### PR TITLE
Major enhancements

### PR DESCRIPTION
**Pull request by mclarence**
I've implemented the new plex authentication method. This is far from perfect and requires more work. Please excuse the way I have written the code in some areas. I have not used retrofit and rxjava before. You may want to change the way i've done it.

When logging in, you don't have to enter username or password. Just press sign in and in the logs it will show a URL, where the user should open and login through. Currently when nothing is playing in plex, an error appears. 

#12

### CODE REVIEW

**Comment by Ombrelin** [comment]
Sound really nice ! I'll have a look a it this weekend. Do yo have any documents or postman collection that could help me understand this new authentication process ?
No problem ! I am very thankful for your interest and substantial contributions 😊

**Comment by mclarence** [comment]
I've created postman collection here:

https://www.postman.com/warped-comet-830856/workspace/plex-authentication-api/overview

**Comment by Ombrelin** [comment]
Hello, that's awesome ! 
I just tested it, and It's very nice. I just had to add a minor fix because one of the server I have on my plex account was blocking the `getSessions` call. The login is much more seamless and the tray thing is awesome !
I have started to do some minor cleanup on my end, will merge it when you think your branch is ready.

As for the tray issue on mac, I came across [that lib](https://github.com/dustinkredmond/FXTrayIcon) which might be worth to look at regarding tray icon implementation. However, I can't debug this issue myself since I do not own a mac myself.

**Comment by mclarence** [comment]
Can you add your fix to my PR?

I will try and use the library you linked.

**Comment by Ombrelin** [comment]
I could not add changes to your branch since it's on your forked repo but I just pushed a "new auth" branch with my fixes which you may merge into your branche.

**Comment by mclarence** [comment]
ok, everything should be working now. please verify on your end.

**Comment by Ombrelin** [comment]
Looking into it ; looks great so far.
Just a question : is there a specific reason of why you decided to put the logs in a new window ?

**Comment by mclarence** [comment]
I felt like it was unnecessary for the user to see the logs. If there is any issue, they can just open the log and go from there.

**Comment by Ombrelin** [comment]
Okay, I agre with you. I'll just apply the theme's CSS in order to have everything in sync visually. 
I'll do the merge & release this week

**Comment by mclarence** [comment]
May I propose changing the application's icon to something else? Sometimes I get confused if it is the plex app or not.

**Comment by Ombrelin** [comment]
I totally agree ! I'll look into it, don't hesistate if you have any input

**Comment by mclarence** [comment]
icon

I think this icon should do. What do you think? [Direct Link](https://images2.imgbox.com/15/df/Cv2CETPf_o.png)

**Comment by Ombrelin** [comment]
I hired one of my friend who has graphic design skills to create  an icon

**Pull request merged**
